### PR TITLE
token based login for flash scicat

### PR DESCRIPTION
**Pull request by zain-sohail**
Suggested by @kutnyakhov in #345 , simple fix that only affects the flashloader so would be nice to merge quickly.

I will try to add tests, but might be tricky considering it's an API call.

### CODE REVIEW

**Comment by zain-sohail** [comment]
I have added tests by mocking the requests from server. 

The pytest fixture library for this is requests-mock. 
Tests seems to run but on Pypi it said that it's only valid up to python 3.10 so I am not fully certain if it works on 3.11

**Comment by rettigl** [comment]
I added a manual workflow trigger for the multiversion tests, and ran them on this branch, seems to work fine also with 3.11

**Review by rettigl — APPROVED** [review]
LGTM. Good addition would be, as said, a mechanism to provide the token directly from the example notebook in a prepared fashion, so one does not have to edit config files all the time.

File: sed/loader/flash/loader.py [hunk 1]
```diff
@@ -924,7 +925,7 @@ def read_dataframe(
 
         df, df_timed = self.parquet_handler(data_parquet_dir, **kwds)
 
-        metadata = self.parse_metadata() if collect_metadata else {}
+        metadata = self.parse_metadata(**kwds) if collect_metadata else {}
```
Comment (rettigl) [inline sed/loader/flash/loader.py:928]: Did you test this? You pass the **kwds dict to both parquet_handler and parse_metadata, neither of which accept **kwds arguments. I would expect this to always lead to an unexpected keyword argument exception

Comment (zain-sohail) [reply sed/loader/flash/loader.py:929]: I didn't test the loader function before and you were right. I have fixed this now

**Review by rettigl — APPROVED** [review]
I cannot really test this, as I don't have a scicat token, and don't know which URL to use. None if the FLASH metadata stuff is really documented in examples, I suggest this should be still added, so users understand what to do. 
From reading the code, I think it should be fine.

File: sed/loader/flash/loader.py [hunk 2]
```diff
@@ -924,7 +926,7 @@ def read_dataframe(
...
```
[the remark this answers is not in the document]
Comment (zain-sohail) [reply sed/loader/flash/loader.py:929]: Regarding documenting the metadata code in examples, I think it will be done later since scicat is still in test instance.

For **kwds, I don't find a large docstring necessarily useful. For someone going through the API on our docs (or looking at code on IDE), they can see relevant keyword arguments documented for relevant methods.
